In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sn

In [3]:
df=pd.read_csv("dl_set.csv")

In [4]:
print(df.shape)
print(df.columns)
print(df.info())
print(df.isnull().sum())

(53337, 5)
Index(['patent_id', 'title', 'abstract', 'title_clean', 'abstract_clean'], dtype='str')
<class 'pandas.DataFrame'>
RangeIndex: 53337 entries, 0 to 53336
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   patent_id       53337 non-null  str
 1   title           53337 non-null  str
 2   abstract        53337 non-null  str
 3   title_clean     53337 non-null  str
 4   abstract_clean  53337 non-null  str
dtypes: str(5)
memory usage: 2.0 MB
None
patent_id         0
title             0
abstract          0
title_clean       0
abstract_clean    0
dtype: int64

In [5]:
df.head()

,patent_id,title,abstract,title_clean,abstract_clean
0,US10460601B2,Traffic management device and system,A smart traffic control device transmits infor...,traffic management device and system,a smart traffic control device transmits infor...
1,US7877342,Neural network for processing arrays of data w...,A neural network for processing arrays of data...,neural network for processing arrays of data w...,a neural network for processing arrays of data...
2,US5253329,Neural network for processing both spatial and...,Neural network algorithms have impressively de...,neural network for processing both spatial and...,neural network algorithms have impressively de...
3,US5995952,Neural network for providing hints to problem ...,A problem solving unit obtains a solution in a...,neural network for providing hints to problem ...,a problem solving unit obtains a solution in a...
4,US9349092,Neural network for reinforcement learning,A neural model for reinforcement-learning and ...,neural network for reinforcement learning,a neural model for reinforcement learning and ...

In [6]:
df.isnull().sum()

patent_id         0
title             0
abstract          0
title_clean       0
abstract_clean    0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df['patent_id'].duplicated(keep=False).sum()

np.int64(0)

In [9]:
print(df.shape)
print(df['patent_id'].nunique())

(53337, 5)
53337

In [10]:
for col in df.columns:
    print(df[col].describe())
    print(50*'-')
    print(df[col].duplicated().sum())
    print(50*'-')
    print(df[col].isnull().sum())
    print(50*'-')
    print(df[col].nunique())

count            53337
unique           53337
top       US10460601B2
freq                 1
Name: patent_id, dtype: object
--------------------------------------------------
0
--------------------------------------------------
0
--------------------------------------------------
53337
count                    53337
unique                   52246
top       Semiconductor device
freq                        22
Name: title, dtype: object
--------------------------------------------------
1091
--------------------------------------------------
0
--------------------------------------------------
52246
count           53337
unique          52864
top       No content.
freq               98
Name: abstract, dtype: object
--------------------------------------------------
473
--------------------------------------------------
0
--------------------------------------------------
52864
count                    53337
unique                   52087
top       semiconductor device
freq                        23
Name: title_clean, dtype: object
--------------------------------------------------
1250
--------------------------------------------------
0
--------------------------------------------------
52087
count          53337
unique         53007
top       no content
freq             104
Name: abstract_clean, dtype: object
--------------------------------------------------
330
--------------------------------------------------
0
--------------------------------------------------
53007

In [11]:

df[['title','abstract']].duplicated().sum()

np.int64(276)

In [12]:
df.drop_duplicates(subset=['title','abstract'],keep=
                   'first', inplace=True)

print(df[df['abstract'] == 'No content.'])

                  patent_id  \
46618  SMPL-19911021-27178C
46619  SMPL-19911024-852E1B
46620  SMPL-19911114-2F27EB
46621  SMPL-19911217-CAF79B
46622  SMPL-19920111-13F01F
...                     ...
47222  SMPL-19960424-CB5A8A
47223  SMPL-19960424-1AD860
47224  SMPL-19960425-C6BE54
47225  SMPL-19960426-8A5C02
47227  SMPL-19960527-F6543A

                                                   title     abstract  \
46618  Improbed process for the manufacturing of halo...  No content.
46619  Flexible metal/plastic laminate and apparatus ...  No content.
46620        Meta thessis polymerization of cycloolefins  No content.
46621  Colloidal dispersions of cerium (iv) compounds...  No content.
46622  Bactericidal 4.5-dichloro-1.2-dithiol-3-one co...  No content.
...                                                  ...          ...
47222  Lock handle device for withdrawal rotation typ...  No content.
47223                                     High freq. amp  No content.
47224  Liquid crystal display elements and its manufa...  No content.
47225            Linear load current measurement circuit  No content.
47227       Method for aromatizing soluble coffee powder  No content.

                                             title_clean abstract_clean
46618  improbed process for the manufacturing of halo...     no content
46619  flexible metalplastic laminate and apparatus f...     no content
46620        meta thessis polymerization of cycloolefins     no content
46621  colloidal dispersions of cerium iv compounds a...     no content
46622   bactericidal 45dichloro12dithiol3one composition     no content
...                                                  ...            ...
47222  lock handle device for withdrawal rotation typ...     no content
47223                                      high freq amp     no content
47224  liquid crystal display elements and its manufa...     no content
47225            linear load current measurement circuit     no content
47227       method for aromatizing soluble coffee powder     no content

[98 rows x 5 columns]

In [13]:
df.duplicated(subset=['title','abstract']).sum()
df = df[df['abstract'] != 'No content.']

In [14]:
df[df['abstract']=='No content.']

Empty DataFrame
Columns: [patent_id, title, abstract, title_clean, abstract_clean]
Index: []

In [15]:
df.duplicated().sum()

np.int64(0)

In [16]:
for i in df.columns:
    print(f'{i}: {df[i].isnull().sum()}')
    print(f'{i}: {df[i].isna().sum()}')
    print(50*'-')

patent_id: 0
patent_id: 0
--------------------------------------------------
title: 0
title: 0
--------------------------------------------------
abstract: 0
abstract: 0
--------------------------------------------------
title_clean: 0
title_clean: 0
--------------------------------------------------
abstract_clean: 0
abstract_clean: 0
--------------------------------------------------

In [17]:
for col in df.columns:
    print(f'{col}: {df[col].isnull().sum()}')
    print(f'{col}: {df[col].nunique()}')
    print(50*'-')

patent_id: 0
patent_id: 52963
--------------------------------------------------
title: 0
title: 52151
--------------------------------------------------
abstract: 0
abstract: 52863
--------------------------------------------------
title_clean: 0
title_clean: 51954
--------------------------------------------------
abstract_clean: 0
abstract_clean: 52880
--------------------------------------------------

In [18]:
df['abstract_clean']=(df['abstract'].fillna('')
                      .astype(str)
                      .str.lower()
                      .str.replace(r'\s+',' ',regex=True)
                      .str.replace(r'[^a-z0-9\-\./\+\(\)\s]', ' ', regex=True)
                    .str.strip()          
                      )

df['title_clean'] = df['title'].fillna('').astype(str).str.lower().str.replace(r'\s+', ' ', regex=True).str.replace(r'[^a-z0-9\-\./\+\(\)\s]', ' ', regex=True).str.strip()

In [19]:
df.head()

,patent_id,title,abstract,title_clean,abstract_clean
0,US10460601B2,Traffic management device and system,A smart traffic control device transmits infor...,traffic management device and system,a smart traffic control device transmits infor...
1,US7877342,Neural network for processing arrays of data w...,A neural network for processing arrays of data...,neural network for processing arrays of data w...,a neural network for processing arrays of data...
2,US5253329,Neural network for processing both spatial and...,Neural network algorithms have impressively de...,neural network for processing both spatial and...,neural network algorithms have impressively de...
3,US5995952,Neural network for providing hints to problem ...,A problem solving unit obtains a solution in a...,neural network for providing hints to problem ...,a problem solving unit obtains a solution in a...
4,US9349092,Neural network for reinforcement learning,A neural model for reinforcement-learning and ...,neural network for reinforcement learning,a neural model for reinforcement-learning and ...

In [20]:
print(df['abstract'].iloc[0])
print(df['abstract_clean'].iloc[0])

A smart traffic control device transmits information to approaching vehicles regarding its current and future state enabling vehicles to control their speed to avoid arriving at the traffic control device until it permits the passage of traffic, thus avoiding stopping, idling and reaccelerating when reaching the traffic control device. In other embodiments the traffic control device or systems receives information from vehicles, transmitting it to other vehicles.
a smart traffic control device transmits information to approaching vehicles regarding its current and future state enabling vehicles to control their speed to avoid arriving at the traffic control device until it permits the passage of traffic  thus avoiding stopping  idling and reaccelerating when reaching the traffic control device. in other embodiments the traffic control device or systems receives information from vehicles  transmitting it to other vehicles.

In [22]:
df['text'] = df['title_clean'] + " " + df['abstract_clean']
df.head()

,patent_id,title,abstract,title_clean,abstract_clean,text
0,US10460601B2,Traffic management device and system,A smart traffic control device transmits infor...,traffic management device and system,a smart traffic control device transmits infor...,traffic management device and system a smart t...
1,US7877342,Neural network for processing arrays of data w...,A neural network for processing arrays of data...,neural network for processing arrays of data w...,a neural network for processing arrays of data...,neural network for processing arrays of data w...
2,US5253329,Neural network for processing both spatial and...,Neural network algorithms have impressively de...,neural network for processing both spatial and...,neural network algorithms have impressively de...,neural network for processing both spatial and...
3,US5995952,Neural network for providing hints to problem ...,A problem solving unit obtains a solution in a...,neural network for providing hints to problem ...,a problem solving unit obtains a solution in a...,neural network for providing hints to problem ...
4,US9349092,Neural network for reinforcement learning,A neural model for reinforcement-learning and ...,neural network for reinforcement learning,a neural model for reinforcement-learning and ...,neural network for reinforcement learning a ne...

In [23]:
# install sentence-transformers if missing
%pip install -q sentence-transformers

from sentence_transformers import SentenceTransformer

[notice] A new release of pip available: 22.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Note: you may need to restart the kernel to use updated packages.

c:\Users\Dell\Desktop\dlmajor\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [24]:
model = SentenceTransformer('all-MiniLM-L6-v2')
text = df['text'].iloc[0]

embedding = model.encode(text)

print(embedding.shape)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 2158.53it/s]

(384,)

In [28]:
sample_texts = df['text'].head(100).tolist()

embeddings = model.encode(
    sample_texts,
    show_progress_bar=True
)
print(embeddings.shape)

Batches: 100%|██████████| 4/4 [00:03<00:00,  1.24it/s]

(100, 384)

In [29]:
all_texts = df['text'].tolist()

embeddings = model.encode(
    all_texts,
    batch_size=32,
    show_progress_bar=True
)
print(embeddings.shape)

Batches: 100%|██████████| 1656/1656 [2:11:13<00:00,  4.75s/it]

(52963, 384)

In [35]:
np.save("patent_embeddings.npy", embeddings)

In [36]:
patent_embeddings = pd.DataFrame(embeddings)
patent_embeddings.insert(0, "patent_id", df["patent_id"].values)

patent_embeddings.to_csv("patent_embeddings.csv", index=False)
np.save("patent_embeddings.npy", embeddings)

print("Saved patent_embeddings.npy and patent_embeddings.csv")

Unexpected exception formatting exception. Falling back to standard exception

Traceback (most recent call last):
  File "c:\Users\Dell\Desktop\dlmajor\.venv\Lib\site-packages\IPython\core\interactiveshell.py", line 3748, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\Dell\AppData\Local\Temp\ipykernel_908\496889843.py", line 4, in <module>
    patent_embeddings.to_csv("patent_embeddings.csv", index=False)
  File "c:\Users\Dell\Desktop\dlmajor\.venv\Lib\site-packages\pandas\core\generic.py", line 3988, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell\Desktop\dlmajor\.venv\Lib\site-packages\pandas\io\formats\format.py", line 1025, in to_csv
    csv_formatter.save()
  File "c:\Users\Dell\Desktop\dlmajor\.venv\Lib\site-packages\pandas\io\formats\csvs.py", line 272, in save
    self._save()
  File "c:\Users\Dell\Desktop\dlmajor\.venv\Lib\site-packages\pandas\io\formats\csvs.py", line 277, in _save
    self._save_body()
  File "c:\Users\Dell\Desktop\dlmajor\.venv\Lib\site-packages\pandas\io\formats\csvs.py", line 315, in _save_body
    self._save_chunk(start_i, end_i)
  File "c:\Users\Dell\Desktop\dlmajor\.venv\Lib\site-packages\pandas\io\formats\csvs.py", line 322, in _save_chunk
    res = df._get_values_for_csv(**self._number_format)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell\Desktop\dlmajor\.venv\Lib\site-packages\pandas\core\frame.py", line 1396, in _get_values_for_csv
    mgr = self._mgr.get_values_for_csv(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell\Desktop\dlmajor\.venv\Lib\site-packages\pandas\core\internals\managers.py", line 629, in get_values_for_csv
    return self.apply(
           ^^^^^^^^^^^
  File "c:\Users\Dell\Desktop\dlmajor\.venv\Lib\site-packages\pandas\core\internals\managers.py", line 445, in apply
    applied = getattr(b, f)(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell\Desktop\dlmajor\.venv\Lib\site-packages\pandas\core\internals\blocks.py", line 629, in get_values_for_csv
    result = get_values_for_csv(
             ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell\Desktop\dlmajor\.venv\Lib\site-packages\pandas\core\indexes\base.py", line 8149, in get_values_for_csv
    values = values.astype(str)
             ^^^^^^^^^^^^^^^^^^
numpy._core._exceptions._ArrayMemoryError: Unable to allocate 12.1 MiB for an array with shape (384, 259) and data type <U32

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Dell\Desktop\dlmajor\.venv\Lib\site-packages\IPython\core\interactiveshell.py", line 2223, in showtraceback
    stb = self.InteractiveTB.structured_traceback(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell\Desktop\dlmajor\.venv\Lib\site-packages\IPython\core\ultratb.py", line 1228, in structured_traceback
    return FormattedTB.structured_traceback(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell\Desktop\dlmajor\.venv\Lib\site-packages\IPython\core\ultratb.py", line 1099, in structured_traceback
    return VerboseTB.structured_traceback(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell\Desktop\dlmajor\.venv\Lib\site-packages\IPython\core\ultratb.py", line 907, in structured_traceback
    formatted_exceptions: list[list[str]] = self.format_exception_as_a_whole(
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell\Desktop\dlmajor\.venv\Lib\site-packages\IPython\core\ultratb.py", line 764, in format_exception_as_a_whole
    records = self.get_records(etb, context, tb_offset) if etb else []
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell\Desktop\dlmajor\.venv\Lib\site-packages\IPython\core\ultratb.py", line 887, in get_records
    for sd_fi in stack_data.FrameInfo.stack_data(
  File "c:\Users\Dell\Desktop\dlmajor\.venv\Lib\site-packages\stack_data\core.py", line 597, in stack_data
    yield from collapse_repeated(
  File "c:\Users\Dell\Desktop\dlmajor\.venv\Lib\site-packages\stack_data\utils.py", line 83, in collapse_repeated
    yield from map(mapper, original_group)
  File "c:\Users\Dell\Desktop\dlmajor\.venv\Lib\site-packages\stack_data\core.py", line 587, in mapper
    return cls(f, options)
           ^^^^^^^^^^^^^^^
  File "c:\Users\Dell\Desktop\dlmajor\.venv\Lib\site-packages\stack_data\core.py", line 551, in __init__
    self.executing = Source.executing(frame_or_tb)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell\Desktop\dlmajor\.venv\Lib\site-packages\executing\executing.py", line 224, in executing
    source = cls.for_frame(frame)
             ^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell\Desktop\dlmajor\.venv\Lib\site-packages\executing\executing.py", line 143, in for_frame
    return cls.for_filename(frame.f_code.co_filename, frame.f_globals or {}, use_cache)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell\Desktop\dlmajor\.venv\Lib\site-packages\executing\executing.py", line 172, in for_filename
    return cls._for_filename_and_lines(filename, tuple(lines))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell\Desktop\dlmajor\.venv\Lib\site-packages\executing\executing.py", line 183, in _for_filename_and_lines
    result = source_cache[(filename, lines)] = cls(filename, lines)
                                               ^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Dell\Desktop\dlmajor\.venv\Lib\site-packages\executing\executing.py", line 113, in __init__
    self.text = ''.join(lines)
                ^^^^^^^^^^^^^^
MemoryError